### ISSUE TITLE
Camera movement

### ISSUE THREAD

**Issue by kevinlinxc** [RiotGames/leaguedirector#9]
I binded camera up to my numpad 8 key. I am used to using creator suite so I thought pressing it would make me zoom forward relative to my current camera position. It started doing that, but when I hold 8, it zooms in slowly and then zooms out slowly even after releasing the key. I think the second part of this is what camera up is actually supposed to do, but I'm not sure why it zooms in initially, as I don't have creator suite running. Additionally, it would be very helpful if the numpad keys were distinguished from the keyboard keys as there are only so many letters that aren't bound already. Thank you for this program, I have no doubt that it will be great with a few iterations.

**Comment by kevinlinxc** [comment]
I found out why. I did not read the read me (oops), apparently numpad 4 5 6 and 8 are the defaults for regular camera movement. I would suggest adding a section in key bindings where those can be changed and displayed.

**Comment by RiotTuxedo** [comment]
It sounds like you've figured this out on your own. Is the only piece of feedback being able to edit the key bindings for camera movement, or is there still feedback you'd like to include about how the camera movement works?

**Comment by kevinlinxc** [comment]
Didn't see the initial reply
, sorry. While it is possible to change the speed of the keys, I would recommend double tapping keys to double the speed while they are held. This gives more flexibility when traveling throughout the map.

**Comment by RiotTuxedo** [comment]
As of patch 9.4, we've released two pieces to help manipulate the camera in replays:

1. The Replay API which can be used by any developer to create camera tools (such as Creator Suite).
2. League Director as an example of how to use the Replay API.

The Replay API is part of the game client itself. League Director is meant to be an example of how to use the Replay API to manipulate the in-game camera during replays. The goal for League Director isn't to mirror the functionality of the Creator Suite or replace it. The primary purpose is to create a starting point for developers to make camera tools for replays using the Replay API. Because the goal is to create a comprehensive sample and a good starting point for developers, we'll be prioritizing bugs and requests toward that end such as macOS support. With that said, this project is open source so it's entirely possible a developer will copy/pasta this project and add features or tweak the functionality like you're suggesting.

**Comment by kevinlinxc** [comment]
I understand. Thank you. I'm in my first year of engineering, and I am
interested in programming. I know c and Javascript. What languages and
tools do I need to know to contribute to director or copy and paste and
make my own version?

**Comment by RiotTuxedo** [comment]
If you click on the blue bar under the commits and branches it'll show the languages included in a repo:

![36373f59c4ecdde6b0450e2bd5c814df](https://user-images.githubusercontent.com/30917923/53676047-25c28280-3c52-11e9-8b04-23f65fc93dbf.png)

And then the [Developing](https://github.com/RiotGames/leaguedirector#developing) section talks about the dependencies.
